#ifndef USER_PROFILE_H
#define USER_PROFILE_H

extern PyObject *g_mod;

const char* TOOL_BAR = "<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
"<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">"
"<style>"
"%s"
"</style>"
"<script>"
"%s"
"</script>"
"<title> Profile </title>"
"</head>"
"<body>"
"<div id=\"wrapper\">"
"<div id=\"navContainer\">"
"%s"
"</div>"
"<div id=\"content\">"
"</div>"
"</div>"
"</body>"
"</html>";

const char* CSS = "body {"
"font: 62.5%/1.5 Verdana, Arial, Helvetica, sans-serif;"
"background: #dddddd;"
"}\n"
"#wrapper {"
"width: 700px;"
"margin: 0 auto;"
"background: #ffffff;"
"}\n"
"#content {"
"padding: 15px 15px 0;"
"border-right: 1px solid #898989;"
"border-bottom: 1px solid #898989;"
"border-left: 1px solid #898989;"
"}\n"
"#navContainer {"
"font: 1.1em Arial, Helvetica, sans-serif;"
"text-align: center;"
"padding: 20px 0 0;"
"border-bottom: 1px solid #909090;"
"background: #dddddd;"
"}\n"
"#navigation ul {"
"padding: 0 0 5px;"
"}\n"
"#navigation li {"
"display: inline;"
"}\n"
"#navigation a:link, #navigation a:visited {"
"text-transform: uppercase;"
"text-decoration: none;"
"color: #000000;"
"background: #bbbbbb;"
"border: 1px solid #898989;"
"padding: 5px 10px;"
"position: relative;"
"margin-right: 5px;"
"}\n"
"#navigation #profilePageLink a:link, #navigation"
"#logoutLink a:visited {"
"margin-right: 0;"
"}\n"
"#navigation a:visited {"
"color: #222222;"
"}\n"
"#navigation a:hover {"
"text-decoration: underline;"
"background: #cccccc;"
"}\n";

const char* JS = "function ready(callback) {\n"
"\tif (document.readyState != 'loading')\n"
"\t\tcallback();\n"
"\telse if (document.addEventListener)\n"
"\t\tdocument.addEventListener('DOMContentLoaded', callback);\n"
"\telse\n"
"\t\tdocument.attachEvent('onreadystatechange', function() {\n"
"\t\t\tif (document.readyState == 'complete')\n"
"\t\t\t\tcallback();\n"
"\t\t});\n"
"\t}\n"
"ready(function() {\n"
"\t\tvar iframe = document.createElement('iframe');\n"
"\t\tdocument.getElementById(\"content\").appendChild(iframe);\n"
"\t\tiframe.setAttribute(\"style\",\"height:100%;width:100%;\");\n"
"\t\tiframe.contentWindow.document.open();\n"
"\t\tiframe.contentWindow.document.write(`%s`);\n"
"\t\tiframe.contentWindow.document.close();\n"
"});\n";

const char* NAV = "<div id=\"navigation\">"
"<ul>"
"<li id=\"profileLink\"><a href=\"#\">Profile</a></li>"
"<li id=\"logoutLink\"><a href=\"#\">Logout</a></li>"
"</ul>"
"</div>";

#endif
